# docker run -it --name mycroft --privileged --device /dev/snd -e DISPLAY=unix$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix -v \
# /dev/dri:/dev/dri -v /dev/shm:/dev/shm -v /etc/machine-id:/etc/machine-id -v /run/dbus:/run/dbus \
# --ulimit rtprio=95 --ulimit memlock=-1 mycroft:latest

mycroft:
  image: mycroftai/docker-mycroft:latest
  privileged: true
  devices:
    - "/dev/snd:/dev/snd"
  volumes:
    - /srv/mycroft:/root/.mycroft
    - ~/.config/pulse/cookie:/root/.config/pulse/cookie
    - ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native
    - /dev/dri:/dev/dri
    - /dev/shm:/dev/shm
    - /etc/machine-id:/etc/machine-id
    - /run/dbus:/run/dbus
  environment:
    - XDG_RUNTIME_DIR=/tmp/xdg_runtime
    - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
  ports:
    - 8181:8181
  ulimits:
    rtprio: 95
    memlock: -1