# docker run -d \
#-v directory_on_local_machine:/root/.mycroft \
#--device /dev/snd \
#-e PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native \
#-v ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native \
#-v ~/.config/pulse/cookie:/root/.config/pulse/cookie \
#-p 8181:8181 \
#--name mycroft mycroftai/docker-mycroft
version: "3"
services:
  mycroft:
    image: mjkaye/mycroft-debian-slim:latest-arm64
    privileged: true
    devices:
      - "/dev/snd:/dev/snd"
    environment:
      - PULSE_SERVER=unix:/run/user/0/pulse/native
      - DISPLAY=unix:0.0
    volumes:
      - /srv/mycroft:/root/.mycroft
      - /srv/mycroft-skills:/opt/mycroft/skills
      - ~/.config/pulse/cookie:/root/.config/pulse/cookie
      - ${XDG_RUNTIME_DIR}/pulse/native:/run/user/0/pulse/native
      - /tmp/.X11-unix:/tmp/.X11-unix
    ports:   
      - 8181:8181
    restart: unless-stopped
