# docker run -d \
#-v directory_on_local_machine:/root/.mycroft \
#--device /dev/snd \
#-e PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native \
#-v ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native \
#-v ~/.config/pulse/cookie:/root/.config/pulse/cookie \
#-p 8181:8181 \
#--name mycroft mycroftai/docker-mycroft

mycroft:
  image: mycroftai/docker-mycroft:latest
  privileged: true
  devices:
    - "/dev/snd:/dev/snd"
  environment:
    - XDG_RUNTIME_DIR=/tmp/xdg_runtime
    - PULSE_SERVER=unix:${XDG_RUNTIME_DIR}/pulse/native
  volumes:
    - /srv/mycroft:/root/.mycroft
    - ~/.config/pulse/cookie:/root/.config/pulse/cookie
    - ${XDG_RUNTIME_DIR}/pulse/native:${XDG_RUNTIME_DIR}/pulse/native
  ports:
    - 8181:8181